// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmG5E8VcoOct99ZXENNTnVjRWxFjfjJRc',
    appId: '1:1018428956081:web:0532bb312541f9a5b67190',
    messagingSenderId: '1018428956081',
    projectId: 'github-auth-4b700',
    authDomain: 'github-auth-4b700.firebaseapp.com',
    storageBucket: 'github-auth-4b700.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN3wGCM0Qg-aOTUMLEbHi2pAtX5oOaYZE',
    appId: '1:1018428956081:android:4967c78beb0fa240b67190',
    messagingSenderId: '1018428956081',
    projectId: 'github-auth-4b700',
    storageBucket: 'github-auth-4b700.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7xi4ojOOfkhnNzqq-54g_J6fIhxMXYvI',
    appId: '1:1018428956081:ios:41e704d227c115c5b67190',
    messagingSenderId: '1018428956081',
    projectId: 'github-auth-4b700',
    storageBucket: 'github-auth-4b700.appspot.com',
    iosClientId: '1018428956081-uopcd7nvt2f4ogoojo3rq4pct48jbud1.apps.googleusercontent.com',
    iosBundleId: 'com.example.githupAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7xi4ojOOfkhnNzqq-54g_J6fIhxMXYvI',
    appId: '1:1018428956081:ios:41e704d227c115c5b67190',
    messagingSenderId: '1018428956081',
    projectId: 'github-auth-4b700',
    storageBucket: 'github-auth-4b700.appspot.com',
    iosClientId: '1018428956081-uopcd7nvt2f4ogoojo3rq4pct48jbud1.apps.googleusercontent.com',
    iosBundleId: 'com.example.githupAuth',
  );
}
